/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package menuHelp;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import menuHelp.PanelHelp.PanelAppInfo;
import menuHelp.PanelHelp.PanelContactUs;

/**
 *
 * @author asus
 */
public class Help extends javax.swing.JInternalFrame {
    GridBagLayout layout = new GridBagLayout();
    PanelAppInfo p1;
    PanelContactUs p2;

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
        p1 = new PanelAppInfo();
        p2 = new PanelContactUs();
        dynamicpanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        dynamicpanel.add(p1, c);
        c.gridx = 0;
        c.gridy = 0;
        dynamicpanel.add(p2, c);
        p1.setVisible(true);
        p2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbtn = new javax.swing.JPanel();
        btnappinfo = new javax.swing.JButton();
        btnCU = new javax.swing.JButton();
        dynamicpanel = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Help");

        panelbtn.setBackground(new java.awt.Color(0, 204, 204));

        btnappinfo.setText("App Info");
        btnappinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnappinfoActionPerformed(evt);
            }
        });

        btnCU.setText("Contact Us");
        btnCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbtnLayout = new javax.swing.GroupLayout(panelbtn);
        panelbtn.setLayout(panelbtnLayout);
        panelbtnLayout.setHorizontalGroup(
            panelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnappinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCU))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        panelbtnLayout.setVerticalGroup(
            panelbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbtnLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnappinfo)
                .addGap(18, 18, 18)
                .addComponent(btnCU)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        dynamicpanel.setBackground(new java.awt.Color(255, 102, 204));

        javax.swing.GroupLayout dynamicpanelLayout = new javax.swing.GroupLayout(dynamicpanel);
        dynamicpanel.setLayout(dynamicpanelLayout);
        dynamicpanelLayout.setHorizontalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        dynamicpanelLayout.setVerticalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dynamicpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dynamicpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUActionPerformed
        // TODO add your handling code here:
        p2.setVisible(true);
        p1.setVisible(false);
        
    }//GEN-LAST:event_btnCUActionPerformed

    private void btnappinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnappinfoActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_btnappinfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCU;
    private javax.swing.JButton btnappinfo;
    private javax.swing.JPanel dynamicpanel;
    private javax.swing.JPanel panelbtn;
    // End of variables declaration//GEN-END:variables
}
